package scaffolder

import (
	"context"
	"fmt"
	"log"

	"github.com/google/go-github/v60/github"
)

// EnableRepoFeatures automatically enables GitHub Discussions and automatic branch cleanup.
func EnableRepoFeatures(ctx context.Context, client *github.Client, owner, repo string) {
	hasDiscussions := true
	deleteBranch := true
	_, _, err := client.Repositories.Edit(ctx, owner, repo, &github.Repository{
		HasDiscussions:      &hasDiscussions,
		DeleteBranchOnMerge: &deleteBranch,
	})
	if err != nil {
		log.Printf("Note: could not update repository settings (may require repository admin permissions): %v", err)
	} else {
		log.Println("Successfully enabled GitHub Discussions and auto-deletion of head branches.")
	}
}

// CreateScaffoldPR creates a new branch, commits the generated files, and opens a PR.
func CreateScaffoldPR(ctx context.Context, client *github.Client, owner, repo string, files map[string]string) (string, error) {
	// Enable discussions and branch cleanup
	EnableRepoFeatures(ctx, client, owner, repo)

	// 1. Get repository details for default branch
	repoObj, _, err := client.Repositories.Get(ctx, owner, repo)
	if err != nil {
		return "", fmt.Errorf("failed to fetch repo: %w", err)
	}
	defaultBranch := repoObj.GetDefaultBranch()
	if defaultBranch == "" {
		defaultBranch = "main"
	}

	// 2. Get the commit SHA of the default branch
	ref, _, err := client.Git.GetRef(ctx, owner, repo, "refs/heads/"+defaultBranch)
	if err != nil {
		return "", fmt.Errorf("failed to get ref for %s: %w", defaultBranch, err)
	}
	baseCommitSHA := ref.Object.GetSHA()

	// 3. Create tree entries for all generated files
	var treeEntries []*github.TreeEntry
	for path, content := range files {
		c := content
		p := path
		treeEntries = append(treeEntries, &github.TreeEntry{
			Path:    &p,
			Mode:    github.String("100644"),
			Type:    github.String("blob"),
			Content: &c,
		})
	}

	tree, _, err := client.Git.CreateTree(ctx, owner, repo, baseCommitSHA, treeEntries)
	if err != nil {
		return "", fmt.Errorf("failed to create git tree: %w", err)
	}

	// 4. Create a commit
	commitMsg := "feat: scaffold open-source contributor guidelines & templates\n\nAutomatically generated by Contributor Bot Action."
	commit, _, err := client.Git.CreateCommit(ctx, owner, repo, &github.Commit{
		Message: &commitMsg,
		Tree:    tree,
		Parents: []*github.Commit{{SHA: &baseCommitSHA}},
	}, &github.CreateCommitOptions{})
	if err != nil {
		return "", fmt.Errorf("failed to create git commit: %w", err)
	}

	// 5. Create new branch
	branchName := "scaffold-oss-guidelines"
	refName := "refs/heads/" + branchName
	newRef := &github.Reference{
		Ref:    &refName,
		Object: &github.GitObject{SHA: commit.SHA},
	}

	// Try to create ref, or update if it already exists
	_, _, err = client.Git.CreateRef(ctx, owner, repo, newRef)
	if err != nil {
		log.Printf("Ref %s might already exist, attempting update...", branchName)
		_, _, err = client.Git.UpdateRef(ctx, owner, repo, &github.Reference{
			Ref:    &refName,
			Object: &github.GitObject{SHA: commit.SHA},
		}, true)
		if err != nil {
			return "", fmt.Errorf("failed to create/update branch %s: %w", branchName, err)
		}
	}

	// 6. Open Pull Request
	title := "feat: scaffold open-source contributor guidelines and governance"
	body := `### Open-Source Community Guidelines & Governance

This pull request was automatically generated by **cbog**. It adds standard open-source governance and template files:

- **` + "`CONTRIBUTING.md`" + `**: Development setup, test guidelines, commit standards, and slash command reference.
- **` + "`CODE_OF_CONDUCT.md`" + `**: Contributor Covenant v2.1 community standards.
- **` + "`SECURITY.md`" + `**: Responsible vulnerability disclosure policy.
- **` + "`LICENSE`" + `**: Open-source license.
- **` + "`.github/PULL_REQUEST_TEMPLATE.md`" + `**: Standardized checklist for incoming pull requests.
- **` + "`.github/ISSUE_TEMPLATE/`" + `**: Structured GitHub Issue Forms for bug reports and feature requests.
- **` + "`.github/cbog.yml`" + `**: Modular governance bot configuration.

---
*Note: Once you review this PR, you can merge it using ` + "`/merge`" + ` or the GitHub web interface.*`

	pr, _, err := client.PullRequests.Create(ctx, owner, repo, &github.NewPullRequest{
		Title: &title,
		Head:  &branchName,
		Base:  &defaultBranch,
		Body:  &body,
	})
	if err != nil {
		return "", fmt.Errorf("failed to open pull request: %w", err)
	}

	return pr.GetHTMLURL(), nil
}
